export const ROW_COUNT = [20, 30, 50];
export const PAGE_COUNT = ROW_COUNT[0];
export const DEFAULT_PAGE = 1;

export const GET_ALBUMS_SUCCESS = "GET_ALBUMS_SUCCESS";
export const GET_ALBUMS_LOADING ="GET_ALBUMS_LOADING";
export const GET_ALBUMS_ERROR = "GET_ALBUMS_ERROR";

export const GET_PHOTOS_SUCCESS = "GET_PHOTOS_SUCCESS";
export const GET_PHOTOS_ERROR = "GET_PHOTOS_ERROR";
export const GET_PHOTOS_LOADING = "GET_PHOTOS_LOADING";

export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_LOADING = "GET_USERS_LOADING";
export const GET_USERS_ERROR = "GET_USERS_ERROR";